version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  mysqlcontainer:
    image: mysql
    environment:
      MYSQL_DATABASE: DockerDatabaseProjectTest
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - "./mysqldocker/Dbscripts/:/docker-entrypoint-initdb.d/" 
    restart: always
  nodeservercontainer:
    build:
      context: .
      dockerfile: nodedocker/Dockerfile
    volumes:
      - ./app-back-nodeJs
      - ./app-back-nodeJs/node_modules
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
    depends_on:
      - mysqlcontainer
    expose:
      - 8080
    command: npm start
    restart: on-failure