version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  mysqlcontainer:
    image: mysql
    container_name: mydb
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: DockerDatabaseProjectTest
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysqldocker/Dbscripts/:/docker-entrypoint-initdb.d/" 
    restart: always
  nodeservercontainer:
    container_name: nodeservercontainer
    build:
      context: .
      dockerfile: nodedocker/Dockerfile
    volumes:
      - ./nodedocker:/nodedocker
      - ./nodedocker/node_modules:/nodedocker/node_modules
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
    depends_on:
      - mysqlcontainer
    command: npm start
    restart: always
  vueservercontainer:
    build:
      context: .
      dockerfile: nodedockerfront/Dockerfile
    volumes:
      - ./nodedockerfront:/nodedockerfront
      - ./nodedockerfront/node_modules:/nodedockerfront/node_modules
    ports:
      - "8081:8081"     
    environment:
      NODE_ENV: development
      PORT: 8081
    depends_on:
      - nodeservercontainer
    restart: always